// This file was generated by lezer-generator. You probably shouldn't edit it.
import { LRParser } from '@lezer/lr';
const spec_Identifier = {
  __proto__: null,
  if: 8,
  to: 20,
  repeat: 28,
  then: 30,
  iterate: 32,
  as: 34,
  return: 36,
  break: 38,
  cry: 40,
  skip: 42,
  init: 44,
  fun: 48,
  operator: 52,
};
export const parser = LRParser.deserialize({
  version: 13,
  states:
    ")SQYQPOOO!TQPO'#DPO!fQPO'#C}OOQO'#DT'#DTO!qQPO'#DTO#bQPO'#DPOOQO'#DP'#DPOOQO'#DW'#DWOOQO'#D['#D[O!lQPO'#C}OOQO'#Cx'#CxQYQPOOO#iQPO'#DOO#zQPO'#DVO$YQPO'#CsO$_QQO'#CuO#iQPO'#C}O#zQPO'#C}O$dQPO,59lO#iQPO,59rO#iQPO,59POOQO,59i,59iO$lQPO,59tO$}QPO,59pOOQO-E6v-E6vO%SQPO'#DPO%ZQPO,59jO%iQPO'#DUO%nQPO,59qO%sQPO,59_O%}QPO,59aO&SQPO,59iO&YQPO,59iOOQO'#Cy'#CyO&_QPO1G/WOOQO1G/W1G/WO&gQPO1G/^O&rQPO1G.kOOQO1G/`1G/`O'TQPO'#DZOOQO1G/[1G/[O'YQPO1G/UOYQPO1G/UO'aQPO1G/]O'fQPO1G.yO'iQPO1G.yO'pQPO1G.{OOQO1G/T1G/TOOQO-E6w-E6wOOQO7+$r7+$rO'zQPO,59uO(SQPO7+$pOOQO7+$p7+$pO(ZQPO7+$wO(bQPO7+$eO(iQPO7+$gO(iQPO7+$gOOQO1G/a1G/aO(pQPO1G/aO(uQPO<<HcO(|QPO<<HROOQO7+${7+${",
  stateData:
    ')T~OpOSPOS~ORPOS[OTTOZRO[RO]SO`]Ob`OcXOdaOeXOh^Oj_O~OUbO{cOusXvsX!PsX~OudOvdO!PeO~O{fOuwXvwX!PwX~OusXvsX!PsX^sX_sX~OYgO~P#PORiOTTOZRO[RO]RO~OTkOZRO[RO]RO~ORmO~OknO~OVqOWsO~OTkOZRO[RO]ROfwO~OTxO~OUbO~P#PO^yO_zOudOvdO~OYgO~Oa{O~OVqO!Pga~PYOV!OO~OudOvdO!P!PO~OVqOW!RO~OudOvdO!Pzi~OudOvdO!PXi^Xi_Xi~OT!SO~O!Pri~PYOR!VO~OVqO!Pgi~PYOV!YO!Pii~PYOT!ZOa![O~O!Prq~PYO!Pyq~PYO!Pgq~PYO!Piq~PYOR!_O~O!Pyy~PYO!Piy~PYO',
  goto: '&p!PPPPPPPPPP!QPPPPPPPPPPPPP!gP!gPP!x#hPPP#r$V$h!QPP%V%u$V$VP&_%r$VwUOZ[`cdmyz|}!O!T!V!W!X!Y!]!^oWOZmyz|}!O!T!V!W!X!Y!]!^QZO^hZ}!T!W!X!]!^Q}mQ!TyQ!W|Q!X!OQ!]!VR!^!YQrbQ|mT!Qr|lYOZmy|}!O!T!V!W!X!Y!]!^R!UzoXOZmyz|}!O!T!V!W!X!Y!]!^nQOZmyz|}!O!T!V!W!X!Y!]!^Qj[Qo`QtcRudvUOZ[`cdmyz|}!O!T!V!W!X!Y!]!^Ql]QpaRvf}ROZ[]`acdfmyz|}!O!T!V!W!X!Y!]!^oVOZmyz|}!O!T!V!W!X!Y!]!^',
  nodeNames:
    '⚠ LineComment Program Identifier if Number ( Parameter ) BinaryExpression to LiteralList LiteralCharList ListIdentifier repeat then iterate as return break cry skip init FunctionDeclaration fun OperatorDeclaration operator Operator',
  maxTerm: 47,
  skippedNodes: [0, 1],
  repeatNodeCount: 2,
  tokenData:
    ")p~RiXY!pYZ#[[]!p]^#[pq!pst#atu#owx$Yxy$zyz%Pz{%U{|%U}!O%U!P!Q%U!Q![&^![!]&w!^!_'t!_!`(b!`!a't!c!}#o!}#O)O#O#P#R#R#S#o#T#o#o$g~#o~!uSp~XY!p[]!ppq!p#O#P#R~#UQYZ!p]^!p~#aO!P~~#fRP~OY#aZ]#a^~#a~#vUR~V~tu#o!Q![#o!c!}#o#R#S#o#T#o#o$g~#o~$]UOY$YZw$Ywx$ox#O$Y#O#P$t#P~$Y~$tO[~~$wPO~$Y~%POU~~%UOW~R%]VkQuPz{%r{|%r}!O%r!P!Q%r!^!_%r!_!`%r!`!a%rQ%wVkQz{%r{|%r}!O%r!P!Q%r!^!_%r!_!`%r!`!a%r~&cQT~!O!P&i!Q![&^~&lP!Q![&o~&tPT~!Q![&o~&zTtu'Z!c!}'Z#R#S'Z#T#o'Z$g~'Z~'bU]~R~tu'Z!Q!['Z!c!}'Z#R#S'Z#T#o'Z$g~'ZR'{VkQvPz{%r{|%r}!O%r!P!Q%r!^!_%r!_!`%r!`!a%rR(iVkQ{Pz{%r{|%r}!O%r!P!Q%r!^!_%r!_!`%r!`!a%r~)RQ!Q![)X#P#Q)k~)[R!O!P)e!Q![)X#P#Q)k~)hP!Q![)O~)pOZ~",
  tokenizers: [0, 1],
  topRules: { Program: [0, 2] },
  specialized: [{ term: 3, get: (value) => spec_Identifier[value] || -1 }],
  tokenPrec: 0,
});
